#ifndef STATE_ENUM_H
#define STATE_ENUM_H

typedef enum
{
    STATE_WIFI_INIT,
    STATE_WIFI_READY,
    STATE_IDLE,
    STATE_USER_DETECTED,
    STATE_DATABASE_VALIDATION,
    STATE_CHECK_IN,
    STATE_CHECK_OUT,
    STATE_ADMIN_MODE,
    STATE_VALIDATION_FAILURE,
    STATE_ERROR
} state_t;

#endif // STATE_ENUM_H