name: Auto Versioning, Build, and Release

on:
  push:
    branches:
      - framework  # Trigger on push to `main` branch

jobs:
  release-detection:
    runs-on: ubuntu-latest
    outputs:
      RELEASE: ${{ steps.check_release.outputs.RELEASE }}
      DEV_RELEASE: ${{ steps.check_dev_release.outputs.DEV_RELEASE }}
      MAJOR: ${{ steps.check_major.outputs.MAJOR }}
      MINOR: ${{ steps.check_minor.outputs.MINOR }}
      PATCH: ${{ steps.check_patch.outputs.PATCH }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Check if the commit message contains "release"
      - name: Check if the commit message contains "release"
        id: check_release
        run: |
          COMMIT_MESSAGE="${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"release"* ]]; then
            echo "RELEASE=true" >> $GITHUB_ENV
            echo "::set-output name=RELEASE::true"
          else
            echo "::set-output name=RELEASE::false"
          fi

      # Step 3: Check if the commit message contains "dev-release"
      - name: Check if the commit message contains "dev-release"
        id: check_dev_release
        run: |
          COMMIT_MESSAGE="${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"dev-release"* ]]; then
            echo "DEV_RELEASE=true" >> $GITHUB_ENV
            echo "::set-output name=DEV_RELEASE::true"
          else
            echo "::set-output name=DEV_RELEASE::false"
          fi

      # Step 4: Set the version increment based on commit message
      - name: Check if the commit message contains "major"
        id: check_major
        run: |
          COMMIT_MESSAGE="${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"major"* ]]; then
            echo "::set-output name=MAJOR::true"
          else
            echo "::set-output name=MAJOR::false"
          fi

      - name: Check if the commit message contains "minor"
        id: check_minor
        run: |
          COMMIT_MESSAGE="${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"minor"* ]]; then
            echo "::set-output name=MINOR::true"
          else
            echo "::set-output name=MINOR::false"
          fi

      - name: Check if the commit message contains "patch"
        id: check_patch
        run: |
          COMMIT_MESSAGE="${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"patch"* ]]; then
            echo "::set-output name=PATCH::true"
          else
            echo "::set-output name=PATCH::false"
          fi

  build:
    runs-on: ubuntu-latest
    needs: release-detection
    if: ${{ needs.release-detection.outputs.RELEASE == 'true' || needs.release-detection.outputs.DEV_RELEASE == 'true' }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the ESP-IDF Project
      - name: Build ESP-IDF Project
        run: docker run --rm \
              -v $GITHUB_WORKSPACE:/project \
              -w /project \
              -e HOME=/tmp \
              jjsprandel/scan:v1.0 idf.py build

      # Step 3: Upload the release artifacts (for normal release)
      - name: Upload Release Artifacts
        if: ${{ needs.release-detection.outputs.RELEASE == 'true' }}  # Only for normal release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*.bin
            build/*.elf
            build/*.map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload Dev Release Artifacts (for dev-release)
      - name: Upload Dev Release Artifacts
        if: ${{ needs.release-detection.outputs.DEV_RELEASE == 'true' }}  # Only for dev-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*.bin
            build/*.elf
            build/*.map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Upload build artifacts for non-release pushes
      - name: Upload Build Artifacts
        if: ${{ needs.release-detection.outputs.RELEASE == 'false' && needs.release-detection.outputs.DEV_RELEASE == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/**/*.bin
            build/*.elf
            build/*.map

