name: Compile and Link Steps

on:
  push:
    branches: [ "framework" ]
  pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run idf.py build
      run: docker run --rm -v ${{ github.workspace }}:/project -w /project -e HOME=/tmp espressif/idf idf.py build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp-idf-build
        path: build/